import DB_Handler
#How to use
#DB_Handler.CallDB(List)
#This takes a list of commands

# Starting Values
# These are the values the system requires to run pulled from DB
Users = []

# Generated values


# These values are generated by functions 


#Dictionary for storage of Difficulty
Cards = {}

# functions
def RetrieveUsers(user):
    user_info = DB_Handler.SearchDB("users", "username", user)
    for i in user_info:
        print(i)
        return(i)

def startup():
    name = input("Eneter your username: ")
    user = RetrieveUsers(name)
    if user is None:
        name = input("Enter your username: ")
        password = input("Enter your password: ")
        DB_Handler.InsertIntoDB("users", (name, password))
        startup()
    password = input("Enter your password: ")
    if password == user[1]:
        print("complete")
    else:
        print("Wrong password try again")
        startup()


#main
startup()